### ISSUE TITLE
H69K 内置sata硬盘不能识别

### ISSUE THREAD

**Issue by Entruv1** [2253845067/Actions-OpenWrt#2]
如题，其他固件可以识别，刷这个fdisk-i 识别不出来，麻烦修正下，谢谢

**Comment by 2253845067** [comment]
> 如题，其他固件可以识别，刷这个fdisk-i 识别不出来，麻烦修正下，谢谢

这是lede默认6.1内核的问题，你可以自己fork仓库，修改一下，编译5.15内核就可以了

**Comment by Entruv1** [comment]
已经fork了，请问一下要怎么修改？谢谢啊

**Comment by 2253845067** [comment]
> 已经fork了，请问一下要怎么修改？谢谢啊

现在可以试试了
